---
title: "BookOfR16-18"
author: "Suz"
date: '2019 10 16 '
output: html_document
---
#16.1

```{r}
#a
dbinom(x=1,size=13,prob=3/4)
#barplot(x.prb)

#b
dbinom(x=13,size=13,prob=3/4)

#c
1-pbinom(q=9, size=13,prob=3/4)

#d
sum(dbinom(x=1:3, size=13, prob=3/4))
pbinom(q=3, size=13, prob=3/4)

#e
pbinom(q=8, size=13, prob=3/4)

#f
obj <- rbinom(n=10, size=13, prob=3/4)
mean(obj)


#g
sd(obj)

```


#16.2

```{r}
#a
1-ppois(q=100,107)

#b
dpois(0,107)

#c
barplot(dpois(x=60:150,lambda=107))

#d

hist(rpois(260, 107))

```

#16.3
```{r}
#a
punif(5.5,3,70)

#b
qunif(0.85, 3, 70)

#c
mymean<-mean(seq(3,70))
mysd<-sd(seq(3,70))
mysd
#d
half_min<-mymean-mysd/2
half_max<-mymean+mysd/2
punif(half_max, 3, 70)-punif(half_min, 3,70)

#e
barplot(dunif(3:70,3,70))

#f
s<-runif(10,3,70)
quantile(s, 0,85)

s2<-runif(1000,3,70)
quantile(s2, 0,85)

```


#16.4
```{r}
#a
1-pnorm(20,17,4.5)
pnorm(10,17,4.5)-pnorm(5,17,4.5)
qnorm(0.9,17,4.5)

fakedata <-seq(17-4*4.5, 17+4*4.5)
normdata<-dnorm(fakedata, 17, 4.5)
plot(normdata)
abline(v=10)


#b
pnorm(11,10,2)-pnorm(9.5,10,2)
dnorm(c(9.5,11),10,2)
qnorm(0.025, 10,2)

```

#16.5
```{r}

#a
l <-3500/365.25
x<-seq(0,1, length.out = 100)
plot(x,dexp(x,l),type="l")
abline(v=0,col="gray")
abline(h=0,col="gray")

pexp(30,l/24/60)
qexp(0.9,l/24) #l=days *24 hours

#b
pexp(5, 1/11)
pexp(6,1/9)
1-pexp(15, 1/11)
1-pexp(15,1/9)
```


#17.1
```{r}
mean<-41.1
sd<-11.3

#a
a<-sd/sqrt(6)
a

#b
pnorm(55, mean, a) - pnorm(45,mean, a)

#c
pnorm(65/2, mean, a)

#d
n<-140
p<-0.35

n*p >= 30
#e

myssd<-sd(seq(140))

xs<-myssd/sqrt(n)
1-pnorm(0.4, p, xs)

#f
qnorm(0.9,p,xs)
qnorm(0.1,p,xs)

#g
sx<-34.51/sqrt(63)
sx
1-pt(40-37.8/sx,63-1)
pt(30-37.8/sx,63-1)
pt(40-37.8/sx,63-1)
```



#17.2
```{r}
n<-34
x<-14.22
sd<-2.9
#a

aa<-1-0.1/2
aa
critval<-qnorm(aa)
x+c(-1,1)*critval*sd/sqrt(n)

#b

critval2<-qt(aa,df=n-1)
x+c(-1,1)*critval2*2.9/sqrt(n)


#c 
n<-400

p.left <- 37/n
p.se <- sqrt(p.left*(1-p.left)/n)
qnorm(0.99)
p.left+c(-1,1)*qnorm(0.99)*p.se
#d
p.am <-11/n
p.se2 <- sqrt((p.left+p.am)*(1-(p.left+p.am)/n))
p.left+p.am+c(-1,1)*qnorm(0.99)*p.se2




```


#18.1




```{r}
#a
n<-73
mu<-3.5
test<-3.97
sd<-2.21
a<-0.05
se<-sd/sqrt(n)
t<-(test-mu)/se
pval<-pt(t,df=n-1)
pval>=0.05

test+c(-1,1)*qt(0.975,n-1)*se

#b
t.test(quakes$mag,mu=4.3,alternative="greater")

#c
len<-length(quakes$mag)
mean(quakes$mag)+c(-1,1)*qt(0.99,len-1)*(sd(quakes$mag)/sqrt(len))

#interval does not contain 4.3
```


#18.2
```{r}

```


#18.3
```{r}

```

#18.4
```{r}

```

#18.5
```{r}

```

#18.6
```{r}

```

