---
title: "BookOfR_CH10-12"
author: "Suz"
date: '2019 9 26 '
output: html_document
---
#10.1

```{r}
vec1 <- c(2,1,1,3,2,1,0)
vec2 <- c(3,8,2,2,0,0,0)

if((vec1[1]+vec2[2])==10){ cat("Print me!") }
if(vec1[1]>=2&&vec2[1]>=2){ cat("Print me!") }
if(all((vec2-vec1)[c(2,6)]<7)){ cat("Print me!") }
if(!is.na(vec2[3])){ cat("Print me!") }

res <-ifelse(vec1+vec2>3, vec1*vec2, vec1+vec2)


mymat <- matrix(as.character(1:16),4,4)
mymat <- matrix(c("DANDELION","Hyacinthus","Gerbera",
"MARIGOLD","geranium","ligularia",
"Pachysandra","SNAPDRAGON","GLADIOLUS"),3,3)
mymat <- matrix(c("GREAT","exercises","right","here"),2,2,
byrow=T)
```

```{r}
#mymat<-matrix(as.character(1:16),4,4)
#mymat<-matrix(c("DANDALION","Hyacinthus","Gerbera","Marigold","geranium","ligularia","Pachysandra","SNAPRAGON","GLADIOLUS"),3,3)
mymat<-matrix(c("GREAT","exercises","right","here"),2,2,byrow=T)
f<-substr(diag(mymat),1,1)
f
g<-ifelse(f=="G"|f=="g","HERE",diag(mymat))
g

if(any(g=="HERE")){
      diag(mymat)<-g
      
}else{
      mymat<-diag(1,dim(mymat)[1],dim(mymat)[2])
}

```

#10.2
```{r}
mynum<-3
if(mynum==1){
      res<-12
}else if(mynum==2){
      res<-34
}else if(mynum==3){
      res<-56
}else if(mynum==4){
      res<-78
}else{
      res<-NA
}
cat(res)

lowd <- 12.5
medd <- 25.3
highd <- 58.1
doselev <- factor(c("Low","High","High","High","Low","Med",
"Med"),levels=c("Low","Med","High"))

dosage<-rep(lowd,length(doselev))
dosage[doselev=="Med"]<-medd
dosage[doselev=="High"]<-highd 

if(any(doselev=="High")){
  if(lowd>=10){
    lowd <-10
  }
  else{
    lowd <-lowd/2
  }
  if(medd >=26){
    medd <-26
  }

  if(highd<60){
    highd<-60
  }
  else{
    highd<-highd*1.5
  }

 
}else{
    doselev <- factor(doselev[doselev=="Low"]|doselev=="Med",labels=c("S","M"))
   if(lowd<15&med<35){
     lowd<-lowd*2
     medd<-medd+highd
   }
  dosage<-rep(lowd, length(doselev))
  dosage[doselevel=="Large"]<-medd
  }
  
mynum<-3

ifelse(mynum==0,"zero",switch(EXPR=mynum,"one","Two","three","four","five","six","seven","eight","nine"))

```

#10.3


```{r}
loopvec1 <- 5:7
loopvec2 <- 9:6
f<-matrix(NA,length(loopvec1),length(loopvec2))
for (i in length(loopvec1)){
  f[i,]<-loopvec1[i]*loopvec2
}
f

names<-c("Peter","Homer","Lois","Stewie","Maggie","Bart")
new<-rep(NA,length(names))
for (i in 1:length(names)){
  new[i] <-switch(EXPR=names[i],Homer=12,Marge=34,Bart=56,Lisa=78,Maggie=90,NA) 
}

mylist <- list(aa=c(3.4,1),bb=matrix(1:4,2,2),cc=matrix(c(T,T,F,T,F,F),3,2),dd="string here",ee=list(c("hello","you"),matrix(c("hello","there"))),
ff=matrix(c("red","green","blue","yellow")))
#mylist <- list("tricked you",as.vector(matrix(1:6,3,2)))


c<-0
for (i in 1:length(mylist)){
  m<-mylist[[i]]
  if(is.matrix(m)==T){
    c <-c+1
  }
  else{
    if(is.list(m)==T){
      c<-c+1
    }
  }
}
c

```

#10.4
```{r}
#mynumbers <- c(2,2,2,2,5,2)
mynumbers <- 2:20
#mynumbers <- c(10,1,10,1,2)

myfac <- function(int){
  res <- 1
  while(int>0){
    res <-res*int
    int <- int-1
  }
  cat(res,"\n")
}

myfac(5)

mystring <- "R fever"
index <- 1
ecount <- 0
result <- mystring

#substr(mystring,index,index)

while(ecount<2 && index<=nchar(mystring)){
  
  l <- substr(mystring, index, index)
    
  if(l=="e" || l=="E"){
    ecount <- ecount+1
  }
  if(ecount ==2){
    result<-substr(mystring, 1, index-1)
  }
  
  index<-index+1
}
result


```


#10.5
```{r}

foo<-matrix(1:12,4,3)
apply(apply(foo,1,sort,decreasing=TRUE),2,prod)

matlist <- list(matrix(c(T,F,T,T),2,2),
matrix(c("a","c","b","z","p","q"),3,2),
matrix(1:8,2,4))

lapply(matlist,t)

qux <- array(96:1,dim=c(4,4,2,3))
apply(qux[,,2,],3,diag)


apply(apply(qux[,4,,],3,dim),1,sum)

```




#11.1


```{r}
myfib4 <- function(thresh, printme){
  fibseq <- c(1,1)
  counter <- 2
  repeat {
    fibseq <- c(fibseq,fibseq[counter-1]+fibseq[counter])
    counter <- counter+1
    if(fibseq[counter]>thresh){
      break
    }  
  }
  if(printme==TRUE){
    cat(fibseq,", ",sep="")
  }
  else{
    return(fibseq)}
}
```

```{r}
myfib4(thresh=150,printme=TRUE)
myfib4(1000000,T)
myfib4(150,FALSE)
myfib4(1000000,printme=F)
```




```{r}
#b.i
myfac <- function(int){
  res <- 1
  while(int>0){
    res <-res*int
    int <- int-1
  }
  cat(res,"\n")
}

myfac(5)
myfac(12)

#b.ii
myfac2<-function(int){
  if(int>0){
    myfac(int)
  }
  else{
    cat("NaN\n")
  }
}

myfac2(5)
myfac2(12)
myfac2(-6)
```
#11.2


```{r}
#a.
first <- function(P, i,t=12,y, plotit=TRUE,...){
  years <- 1:y
  final <-P*((1+i/(100*t))^(t*years))
  if (plotit == TRUE){
    plot(years,final,type='s',...)
  }
  else{
    return (final)}
}
  
#i  
first(5000,4.4,y=10,plotit = FALSE) 

#ii
first(100,22.9,y=20,plotit=TRUE)


#iii
com<-first(100,22.9,t=1,y=20,plotit = FALSE)
lines(com,col="Red",lty=2)
legend("bottomright",c("20 years", "1 year"),col=c("black", "red"),lty=c(1,2))

```

```{r}
#b.
qu<-function(k1,k2,k3){
  if (missing(k3)|missing(k2)|missing(k1)){
    return('A value is missing')
  }
  t<-((k2^2)-(4*k1*k3))

  if (t < 0){
     return("There's no solution.")
  }
  if (t == 0){
    ans <- (-k2/2*k1)
    return(ans)
  }
    else{
    ans1 <-(-k2-(k2^2-4*k1*k3)^0.5)/(2*k1)
    ans2 <-(-k2+(k2^2-4*k1*k3)^0.5)/(2*k1)
    return(c(ans1,ans2))
  }
}


qu(2,-1,-5)
qu(1,1,1)
qu(1.3, -8, 3.13)
qu(2.25,-3,1)
qu(1.4,-2.2,-5.1)
qu(-5,10.11,-9.9)
qu(1,2)
```


#11.3


```{r}
#a.
foo <- list("a",c("b","c","d","e"),"f",c("g","h","i"))
lapply(foo, function(x){c(x,"!")})

#b.

mf <- function(num){
ans<-1
if(num==0){
  return(ans)
}
else{
  ans <- mf(num-1)*num
  return(ans)}
}

mf(5)
mf(120)
mf(0)
#c.

#geolist function ??? 

```



#12.1
```{r}
#a
mf2 <- function(num){
ans<-1
if(num<0){
  return("error")
}
if(num==0){
  return(ans)
}
else{
  ans <- mf2(num-1)*num
  return(ans)}
}

mf2(5)
mf2(8)
mf2(-8)

#b

mi <- function(x,nonmat="not a matrix",noninv="NA",silent=T){
  finallist <- list()
  if(!is.list(x)){
    return("this is not a list try again")
  }
  if(length(x)==0){
    return("empty list. try again")
  }
  for (i in 1:length(x)){
    if(is.matrix(x[[i]])){
      
      t<-try(solve(x[[i]]),silent=T)
      
      if (class(t)=="try-error"){
          finallist[[i]] <-noninv
      }
      else{
        finallist[[i]] <-t
      }
    }
    else{
      finallist[[i]]<-nonmat
    }
  }
  return(finallist)
}


mi(list(1:4,matrix(1:4,1,4),matrix(1:4,4,1),matrix(1:4,2,2)))
mi(list(1:4,matrix(1:4,1,4),matrix(1:4,4,1),matrix(1:4,2,2)),nonmat = 666,noninv = Inf)
mi(list(diag(9),matrix(c(0.2,0.4,0.2,0.1,0.1,0.2),3,3),
rbind(c(5,5,1,2),c(2,2,1,8),c(6,1,5,5),c(1,0,2,0)),
matrix(1:6,2,3),cbind(c(3,5),c(6,5)),as.vector(diag(2))),noninv = "unsuitable matrix")
mi("hello")
mi(list())

```


#12.2
```{r}
#a
prog_test <- function(n,...){
result <- 0
t1<-sys.time()
progbar <- txtProgressBar(min=0,max=n,...)
for(i in 1:n){
result <- result + 1
Sys.sleep(0.5)
setTxtProgressBar(progbar,value=i)
}
close(progbar)
return(list(result, sys.time()-t1))
}

#b
#i
myfibvectorTRY <- function(nvec){

myfibrec2 <- function(n){
if(n<0){
warning("Assuming you meant 'n' to be positive -- doing that instead")
n <- n*-1
} else if(n==0){
stop("'n' is uninterpretable at 0")
}
if(n==1||n==2){
return(1)
} else {
return(myfibrec2(n-1)+myfibrec2(n-2))
}
}

nterms <- length(nvec)
result <- rep(0,nterms)

progbar <- txtProgressBar(max=nterms,style=3,char=">")

for(i in 1:nterms){
  attempt1<- try(myfibrec2(nvec[i]),silent=T)
  if(class(attempt1) == "try-error"){
    result[i] <-NA
  }
  else{
    result[i] <- attempt1
  }
}
setTxtProgressBar(progbar,value=i)
return(result)
}

myfibvectorTRY(c(3,2,7,0,9,13))

#ii

time_myfibvectorTRY <- function(nvec){
t1<-sys.time()
myfibrec2 <- function(n){
if(n<0){
warning("Assuming you meant 'n' to be positive -- doing that instead")
n <- n*-1
} else if(n==0){
stop("'n' is uninterpretable at 0")
}
if(n==1||n==2){
return(1)
} else {
return(myfibrec2(n-1)+myfibrec2(n-2))
}
}

nterms <- length(nvec)
result <- rep(0,nterms)

progbar <- txtProgressBar(max=nterms,style=3,char=">")

for(i in 1:nterms){
  attempt1<- try(myfibrec2(nvec[i]),silent=T)
  if(class(attempt1) == "try-error"){
    result[i] <-NA
  }
  else{
    result[i] <- attempt1
  }
}
setTxtProgressBar(progbar,value=i)
return(list(result,sys.time()-t1))
}


#fibo

t1<-Sys.time()
len <- 35
fibvals <- numeric(len)
fibvals[1] <- 1
fibvals[2] <- 1
for (i in 3:len) { 
   fibvals[i] <- fibvals[i-1]+fibvals[i-2]
} 
Sys.time()-t1


```







