---
title: "Book22-24"
author: "Suz"
date: '2019 11 2 '
output: html_document
---
#22.1
```{r}
library("boot")
?nuclear
c<-lm(cost~1,data=nuclear)
#c.step<-step(c, scope=.~.+date+t1+t2+cap+pr+ne+ct+bw+cum.n+pt)
#summary(c.step)

g<-data.frame(Iniheight=c(1000,800,600,450,300,200,100),Dist=c(573,534,495,451,395,337,253))
g.null<-lm(Dist~1,data=g)
g.fit1<-lm(Dist~Iniheight,data=g)
g.fit2<-lm(Dist~Iniheight+I(Iniheight^2), data=g)
g.fit3<-lm(Dist~Iniheight+I(Iniheight^2)+I(Iniheight^3),data=g)
g.fit4<-lm(Dist~Iniheight+I(Iniheight^2)+I(Iniheight^3)+I(Iniheight^4),data=g)

#anova(g.null, g.fit1, g.fit2,g.fit3,g.fit4)

library("faraway")
#?diabetes

#chol, age, gender, height, weight,frame, waist, hip, location

new_dia<-na.omit(diabetes)

#is.na(new_dia$age)

d.null<-lm(chol~1, data=new_dia)
d.full<-lm(chol~age*gender*weight*frame+waist*height*hip+location, data=new_dia)

d.step<-step(d.null, chol.~.+age*gender*weight*frame+waist*height*hip+location)
#summary(d.step)

```


#22.2
```{r}
library("boot")
n.null<-lm(cost~1, data=nuclear)
n.1<-update(n.null,formula=.~.+date)
n.2<-update(n.1,formula=.~.+cap)
n.3<-update(n.2,formula=.~.+pt)
n.4<-update(n.3,formula=.~.+ne)

#n.1
#n.2
#n.3
#n.4
summary(n.4)


plot(n.4, which=1)
plot(n.4, which=2)

plot(n.4, which=4)

plot(n.4, which=5)


library("faraway")
dia<-lm(chol~age*frame+waist, data=diabetes)
summary(dia)

plot(dia, which=1)
plot(dia, which=2)

#dia.url<-"http://www.amstat.org/publications/jse/v9n2/4cdata.txt" #doesn't work
#diamonds<-read.table(dia.url)
#names(diamonds)<-c("Carat","Color","Clarity","Cert","Price")

```



#23.1
```{r}
mpg <-lm(mpg~cyl,data=mtcars)
boxplot(mtcars$mpg~mtcars$cyl)

dev1<-matrix(c(2,1,1,3),4,1)
dev2<-matrix(c(1,1,1,1,2,4,3,5),2,4)
dev3<-matrix(c(2,3,3,1,2,3,3,1,2,4,5,1),4,3)
dev.new(height=4,width=4)
layout(mat=dev3)
plot(1,1)
plot(2,2)
plot(3,3)
plot(4,4)
plot(5,5)

dev.new()

interactive.arrow<-function(...,label=NA){
  arrowpoints<-locator(n=2)
  arrows(x0=arrowpoints$x[1],y0=arrowpoints$y[1],x1=arrowpoints$x[2],y1=arrowpoints$y[2],...)
  if(!is.na(label)){
    labelpos<-locator(n=1)
    text(x=labelpos$x[1],y=labelpos$y[1],labels=label,...)
  }
}

boxplot(quakes$mag)
#interactive.arrow(xpd=NA,label="outliers")
```


#23.2
```{r}
#file doesn't work
```


#24
```{r}
library("MASS")
?UScereal
cereal<-UScereal
cereal$shelf<-factor(cereal$shelf)
lv<-levels(cereal$mfr)[levels(cereal$mfr)%in%c("P","N","Q","R")] <- "O"
cereal$mfr<-factor(cereal$mfr, levels = c("G","K",lv))
#cereal

ggplot(cereal, aes(x=calories, y=protein))+geom_point(aes(col=shelf))
ggplot(cereal, aes(x=calories, y=protein))+geom_point(aes(col=shelf))+geom_smooth(method="loess",span=0.90)


```



```{r}
library("car") #car library fails to load
```

