---
title: "Chapter13-15"
author: "Suz"
date: '2019 10 4 '
output: html_document
---

#13.1
#a
i. numeric-discrete
ii. categoric-ordinal
iii. numeric-continuous
iv. categoric-ordinal
v. categoric-nominal
vi. numeric-continuous

#b
i. statistics
ii. statistics
iii. parameter
iv. parameter
v. statistcs


#13.2

```{r}
#a
round(mean(quakes$depth>=300),2)
#b
mean(quakes$mag[quakes$depth>=300])
median(quakes$mag[quakes$depth>=300])
#c
for (i in levels(chickwts$feed)){
  cat(i,":\n",mean(chickwts$weight[chickwts$feed==i]),"\n")
}

#d ?InsectSprays count - numeric discrete, spray categorical-nominal 

#e
insect_count<-table(InsectSprays$count)
insect_count[insect_count==max(insect_count)]

#f

tapply(InsectSprays$count,InsectSprays$spray,FUN=sum)

#g
for (i in levels(InsectSprays$spray)){
  cat(i, ":",mean(((InsectSprays$count[InsectSprays$spray==i]>=5)/sum(InsectSprays$count))*100)," ")
}

#h

```


#13.3

```{r}
#a
quantile(chickwts$weight,c(0.1,0.3,0.9))

#b 
#i. IQR(quakes$depth)
#ii. 
summary(quakes$mag[quakes$depth<=400])
#iii.
depthcat <-cut(x=quakes$depth,breaks=(seq(min(quakes$depth),max(quakes$depth),length=5)),right=F)
levels(depthcat)
#iv.
"mean:"
tapply(quakes$mag,depthcat,mean)
"standard dev:"
tapply(quakes$mag,depthcat,sd)

#v.
tapply(quakes$mag,depthcat,quantile,prob=0.8)

```






#13.4
```{r}
#a
weight<-c(55,85,75,42,93,63,58,75,89,67)
height<-c(161,185,174,154,188,178,170,167,181,178)
gender <-c('f','m','m','f','m','m','f','m','m','f')

cor(weight,height)

#b
#mtcars
plot(mtcars$hp, mtcars$qsec)

"correlation:"
cor(mtcars$hp, mtcars$qsec)

?mtcars
tranfac<-factor(mtcars$am,labels=c("auto","manual"))

library("ggplot2")

qplot(mtcars$hp, mtcars$qsec, color=tranfac)

#cor(mtcars$hp[mtcars$am],mtcars$qsec[mtcars$am])

#c
sc<-chickwts$weight[chickwts$feed=="sunflower"]
plot(sc,seq(0, length(sc),length=12),ylab="chicks",xlab="weight")

sd(sc)
IQR(sc)

#sick chicken is number 6
#sc

plot(sc[-6],seq(0, length(sc),length=11),ylab="chicks",xlab="weight")

```


#14.1

```{r}
#a
hist(InsectSprays$count)
suminsec <- tapply(InsectSprays$count,InsectSprays$spray,sum)

barplot(suminsec, xlab="spray",ylab='dead insects')
pie(suminsec,labels=levels(InsectSprays$spray), col=c("white","gray","black"),main="Insects")


insec.fac <- factor(InsectSprays$spray)

boxplot(InsectSprays$count~insec.fac,
xlab="spray type",ylab="insect bodies",col="gray")

#d
library(ggplot2)
?USArrests


qplot(USArrests$UrbanPop, geom="blank",main="Urban pop",xlab="Urban pop")+geom_histogram(color="black",fill="white",breaks=seq(0,100,10),closed="right")+ geom_vline(mapping=aes(xintercept=c(quantile(USArrests$UrbanPop,0.25),quantile(USArrests$UrbanPop,0.50),quantile(USArrests$UrbanPop,0.75))))+ scale_linetype_manual(values=c(2,3))+labs(linetype="")

dt<- t(as.matrix(USArrests[,-3]))

barplot(dt, names.arg=state.abb, legend.text=row.names(dt))

urbancat<-rep(NA, length(USArrests$UrbanPop))

for (i in 1:length(USArrests$UrbanPop)){
  if (USArrests$UrbanPop[i] > median(USArrests$UrbanPop)){
    urbancat[i]<-1
  }
  else{
    urbancat[i]<-0
  }
}

urbancat

test<-USArrests[-3]
test$urbancat <- urbancat

```

```{r}
d<-quakes$mag

quant<-quantile(d,c(1/3,2/3))
ans<- cut(d, breaks=c(min(d),quant[1],quant[2],max(d)))
#ans


plot(quakes$long,quakes$lat, pch=quant, col=quant)

#legend("bottomleft", col=1:3, pch=1;3, title='test')
```


#15.1
```{r}
#a
(4/52)

#b
#1/4
#independent

#c
#12/51 

#d
(12*52)*(1/2)
#not mutually exclusive.

```




#15.2

#a
i. random dis
ii. random dis
iii. random dis
iv. random cont
v. real dis
Vi. random dis

#b
i.0.41
ii.


```{r}
b.pro<-c(0.1,0.13,0.21,0.41,0.15)
cumsum(b.pro)
```
iii.

```{r}
b<-c(1,2,3,4,5)
b.pro<-c(0.1,0.13,0.21,0.41,0.15)
s<-b*b.pro
s

#iv
sd(s)

#v
sum(b.pro[1:3])

#vi 

barplot(b.pro, names.arg=b)
```





#c

```{r}
#i.

foo<- function(w){
  res<-rep(0, length(w))
  lower.w <- w>=40 & w<=65
  upper.w <- w>65 & w<=90
  res[lower.w]<-(w[lower.w]-40)/625
  res[upper.w]<-(90-w[upper.w])/625
  return (res)
}
#ii.

foo2<-function(w){
  Fw<- rep(0,length(w))
  lower.w <- w>=40 & w<=65
  upper.w <- w>65 & w<=90
  extra.w<-w>90
  
  Fw[lower.w] <- (w[lower.w]^2-80*w[lower.w]+1600)/1250
  Fw[upper.w] <- (180*w[upper.w]-w[upper.w]^2-6850)/1250
  Fw[extra.w] <- 1
  
  return (Fw)
}
#iii.

foo(55.2)
foo2(55.2)

#iv.
1-foo2(60)
#v.
foo2(76.89)-foo2(60.3)
```

#d
Bimod, sym
Trimod, skew
unimod, sym
unimod, skew

